auth:
  existingSecret: wikijs-db-secret
  secretKeys:
    userKey: POSTGRES_USER
    passwordKey: POSTGRES_PASSWORD
  database: wikijsdb

primary:
  nodeSelector:
    kubernetes.io/hostname: bmax04
  persistence:
    enabled: true
    size: 10Gi
    storageClass: local-storage
