global:
  defaultStorageClass: csi-rbd-sc
redmineUsername: admin
redminePassword: admin
redmineLanguage: ja
databaseType:
  postgresql
mariadb:
  enabled: false
postgresql:
  enabled: true
ingress:
  enabled: true
  ingressClassName: cilium
  hostname: redmine.akilab.internal
  pathType: Prefix
  path: /
