extraEnv:
  - name: DB_TYPE
    value: postgres
  - name: DB_HOST
    value: postgresql
  - name: DB_PORT
    value: "5432"
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
        name: wikijs-db-secret
        key: DB_NAME
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: wikijs-db-secret
        key: DB_USER
  - name: DB_PASS
    valueFrom:
      secretKeyRef:
        name: wikijs-db-secret
        key: DB_PASS
